### ISSUE TITLE
Should we deregister 2003? And how to deregister if yes

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-parachain#107]
Require root to unlock?

https://github.dev/paritytech/polkadot/blob/d5f16df743931d535441f28c605e619c16b971a3/runtime/common/src/paras_registrar.rs#L323

https://github.dev/paritytech/polkadot/blob/d5f16df743931d535441f28c605e619c16b971a3/runtime/common/src/paras_registrar.rs#L458

https://polkadot.subscan.io/extrinsic/11013504-2

If not, use it for paraid swap?

**Comment by acgxv** [comment]
Keep 2003 for future usage.

#116
