### ISSUE TITLE
Swap ParaId Solution

### ISSUE THREAD

**Issue by aurexav** [darwinia-network/darwinia-parachain#116]
We could use [`swap`](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/paras_registrar.rs#L274) call to swap the 2046 and 2003 `ParaId`.

`swap` call will [check there is at least one a parachain](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/paras_registrar.rs#L284).
So, we can not swap two parathreads.
We need to wait for 2046 to become a parachain.

`swap` [requires `ParaId`'s owner or the root origin](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/paras_registrar.rs#L275).
But if we use `ParaId`'s owner account, it will fail at [checking lock](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/paras_registrar.rs#L466).
[`force_remove_lock`](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/paras_registrar.rs#L323) also requires root origin.
All in all, calling with root is the only option for us.

Also, we need to replace the old genesis of 2003 with the new one.
The calls that we need are [`force_set_current_code`](https://github.com/paritytech/polkadot/blob/master/runtime/parachains/src/paras/mod.rs#L722) and [`force_set_current_head`](https://github.com/paritytech/polkadot/blob/master/runtime/parachains/src/paras/mod.rs#L749).

P.S. do we want to unlock the 2003 by the way?

Finally:
```
polkadot.democracy.note_preimage.utility.batch {
	unlock(2003),
	set_code(2003),
	set_head(2003),
}
swap(2003, 2046)

// deprecated
// polkadot.democracy.note_preimage.utility.batch {
//     unlock(2003), // optional
//     set_code(2003),
//     set_head(2003),
//     swap(2003, 2046),
// }
```

**Comment by hackfisher** [comment]
What's the root of 2003?

**Comment by acgxv** [comment]
> What's the root of 2003?

Both's owners are DarwiniaDev.

But we need root (referenda).

**Comment by hackfisher** [comment]
We prefer to unlock 2003, what's the genesis and code for new 2003 BTW.

It will be our parachain, should we include the scope of Crab 2.0 or not?

**Comment by acgxv** [comment]
> We prefer to unlock 2003, what's the genesis and code for new 2003 BTW.

We could use the same one as 2046.

> It will be our parachain, should we include the scope of Crab 2.0 or not?

It totally depends on if we are ready to move the entire Crab to Crab Parachain.
