### ISSUE TITLE
The memory cannot be released for version v5.3.1

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/darwinia-parachain#133]
![image](https://user-images.githubusercontent.com/37804932/180352456-75d4839b-0795-41ad-9599-1affeeeeab68.png)

![image](https://user-images.githubusercontent.com/37804932/180352506-6ca785a7-a837-4460-b90a-87733e66be30.png)

The data of Crab Parachain RPC node monitor

**Comment by fewensa** [comment]
![image](https://user-images.githubusercontent.com/37804932/180359649-49411818-b731-404e-bfb0-32c850ad494c.png)
This is a monitoring graph for Crab Collator when the scheduled restart is turned off.

**Comment by acgxv** [comment]
A normal Kusama node takes around 6G.

I think this is reasonable.

Also, I have tested with the latest code. 
mem-avg 5G.
