### ISSUE TITLE
Release CI Generate Code Hash

### ISSUE THREAD

**Issue by aurexav** [darwinia-network/darwinia-parachain#83]
We don't use proposal hash on parachain.

<img width="1746" alt="image" src="https://user-images.githubusercontent.com/16152305/170939909-fec31cd2-e072-4017-b032-e55579d1cb9e.png">

**Comment by acgxv** [comment]
<img width="2219" alt="image" src="https://user-images.githubusercontent.com/16152305/180141737-0ef5022a-9029-4b41-8671-27297039d141.png">

**Comment by acgxv** [comment]
We should use blake2_256 in the release detail.
