### ISSUE TITLE
Remove or replace sudo with multisig after supporting remote governance.

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-parachain#90]

**Comment by xiaoch05** [comment]
Is this design reasonable?

![remote_governance](https://user-images.githubusercontent.com/15799431/173784844-b193b958-1d0c-4483-991e-1fda297bbc89.svg)

**Comment by hackfisher** [comment]
Yes, and please note that we need a special account id `RootAccountForPayments ` (configured by bridge) to pay the message fees for Root.

Related: https://github.com/darwinia-network/darwinia-messages-substrate/issues/99

**Comment by hackfisher** [comment]
> Is this design reasonable?
> 
> ![remote_governance](https://user-images.githubusercontent.com/15799431/173784844-b193b958-1d0c-4483-991e-1fda297bbc89.svg)

One important use case would be authorizeUpgrade some codeHash:

![image](https://user-images.githubusercontent.com/1070122/173788176-e9cf8450-849c-48a6-95de-bad2762d0715.png)

**Comment by hackfisher** [comment]
And further more, if we want to make it better, we also need to consider some conner case and risks such as the cases of Grandpa stalled in Crab. 

In this case, Crab will probably call `note_stalled` and the `crab_bridge_grandpa` will be required to reset and init its `BestFinalizedHeader` using Root in this case before any bridges massage can be received.

If there are no other pallet support dispatch as Root such as Sudo, then we will be stuck here.

So we might need to add fallback strategy here, if the bridge is not working, the `governance pallet` on Crab parachain might need another fallback/owner origin, which can be set by runtime, and this origin can also dispatch as Root.

We can add an transaction pause pallet to work as assistant for emergency protect for this owner origin.

**Comment by xiaoch05** [comment]
> And further more, if we want to make it better, we also need to consider some conner case and risks such as the cases of Grandpa stalled in Crab.
> 
> In this case, Crab will probably call `note_stalled` and the `crab_bridge_grandpa` will be required to reset and init its `BestFinalizedHeader` using Root in this case before any bridges massage can be received.
> 
> If there are no other pallet support dispatch as Root such as Sudo, then we will be stuck here.
> 
> So we might need to add fallback strategy here, if the bridge is not working, the `governance pallet` on Crab parachain might need another fallback/owner origin, which can be set by runtime, and this origin can also dispatch as Root.
> 
> We can add an transaction pause pallet to work as assistant for emergency protect for this owner origin.

Yes it's important to consider this conner case.
You mean we need reset the bridge to restart it when error accured?
I think the owner of the pallet `bridge-grandpa` can be the rescuer. The prerequisite is that the bridge can be made to work properly by reinitializing it.
https://github.com/darwinia-network/darwinia-messages-substrate/blob/main/modules/grandpa/src/lib.rs#L195

**Comment by hackfisher** [comment]
Currently, bridge-grandpa require `BestFinalizedHeader` being removed from storage using Root first before re-initialization. It does not support any other specific origin for doing that.

And because I'm worried about other possible flaws might exist in message protocol(or upcoming upgrade) will cause Root stuck there, so I prefer to set Crab parachain's governance pallet's owner origin(can dispatch as Root) to some multisig or collective instead to avoid single point of failure and work as a redundant governance choice.

If in that case, I'm thinking maybe we should keep bridge-grandpa pallet simple without modifying it.

**Comment by xiaoch05** [comment]
cc @AurevoirXavier 
1. use bridge_messages::send_message directly to send s2s message to parachain
2. message payload is generated offchain
3. the fee is from treasury, deposit to `RootAccountForPayments` before send_message(maybe we need to use batch call)
4. accept_remote_call split to two dispatch call, one accept the bridge remote call, the other accept the special origin as rescuer such as the Multi-signature account.
